elearning/auth_django/urls.py
# The views used below are normally mapped in django.contrib.admin.urls.py
# This URLs file is used to provide a reliable view deployment for test purposes.
# It is also provided as a convenience to those who want to deploy these URLs
# elsewhere.

from django.contrib.auth import views
from django.urls import path

app_name = 'auth_django'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

elearning/elearning/urls.py
from django.contrib import admin, auth
from django.urls import path  # previously called url
from django.urls import re_path, include

from rest_framework import routers

# testing for django.contrib.auth.urls namespace problem workaround
import auth_django.urls as auth_urls

# this thing is only imported at runtime?
from students.views import student_detail
from courses.views import (my_first_view,
                           my_rendered_view,
                           course_detail,
                           course_list,
                           course_add,
                           do_section,
                           do_test,
                           show_results)
from api.views import UserViewSet, SectionViewSet

# this router is from rest_framework, that connects the
# django-rest-framework's ViewSets methods to django itself.
# steps:
# 1. make a router, and register the viewsets (django rest framework will solve everything else)
# 2. in urlpatterns, make a pattern that links to router.urls (managed by rest_framework so no worries)
# 3. edit stuff in the ViewSet class instead of views
# 3a. the guy magically mixed the classes from api.views into courses.views and students.views
# 3b. but splitting it into a separate 'app' that represents the django-rest-framework library method
#     keeps it conceptually separate
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'sections', SectionViewSet)

# ^$ means this applies to absolutely anything in the multiline input. ^ start of line, $ means end of line
# url patterns are things that connect urls to the views (the functions that do things), so you can define
# which url pattern here does what function
# this is the map function???? does it use mapreduce?
# the <who> means a named group called 'who'

# there's some namespace shit between django 1.11 and 2.0 that makes the namespace part impossible to do
# without editing django's source code. workaround is to copy paste its urlpattern into another 'app' that only
# has the urls. namespaces make sure that when django backtracks to find urls it doesn't confuse itself with
# views with same names under different apps
# (like '/login/' under elearning app that goes to admin and student login vs
#  '/login/' under elearning2 app that goes into another login)
# ref : https://docs.djangoproject.com/en/2.0/topics/http/urls/
# ref2: https://code.djangoproject.com/ticket/28691
# ref3: https://stackoverflow.com/questions/41464477/how-to-properly-configure-root-urlconf

urlpatterns = [
    path('admin/', admin.site.urls),

    # this just imports the list of urlpatterns inside django's contrib.auth.urls file
    path('', include(auth_urls, namespace='auth_django')),

    # the below only works for function based views (defined by ourselves)
    #re_path(r'^course_detail/(?P<course_id>\d+)/$', course_detail, name='course_detail'),
    # a class based view has their own naming conventions
    re_path(r'^course_detail/(?P<pk>\d+)/$', course_detail, name='course_detail'),
    path('student_detail/', student_detail, name='student_detail'),

    re_path(r'^section/(?P<section_id>\d+)/$', do_section, name='do_section'),
    re_path(r'^section/(?P<section_id>\d+)/test/$', do_test, name='do_test'),
    re_path(r'^section/(?P<section_id>\d+)/results/$', show_results, name='show_results'),

    path('course_add/', course_add, name='course_add'),
    re_path(r'^course_list/$', course_list),

    # the django-rest-framework library part. doesn't have to be /api, could be /whateverfloatsyourboat
    re_path(r'^api/', include(router.urls)),

    re_path(r'^(?P<who>.*)/$', my_rendered_view),
    path('liqun/', my_first_view),
    path('', course_list),
]

elearning/elearning/templates/base.html
<!-- loads django specific staticfiles library -->
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django E-learning</title>
    <!-- all local versions of bootstrap css, jquery and bootstrap javascript -->
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                {% if request.user.is_authenticated %}
                <p>
                    Logged in as <a href="{% url 'student_detail' %}">{{ request.user.username }}</a>
                    (<a href="{% url 'auth_django:logout' %}">Logout</a>)
                </p>
                {% else %}
                <p>
                    <a href="{% url 'auth_django:login' %}">Login</a>
                </p>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- this Default Content block will be overwritten by the child templates -->
    {% block "content" %}Default Content{% endblock %}
    <script src="{% static 'jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
</body>
</html>